"""Simulate multinode training via pandas_udf — each row carries model bytes.

Every row in the run plan emits its own model_blob (binary) — this is what a
real distributed training pipeline would produce, where each worker trains a
model per (region, sku) and emits the serialized bytes. For benchmarking we
broadcast ONE reference model and reuse the bytes across all rows, but the
output schema and serialization path stay realistic.

Mock params and metrics self-populate via `TrainedModelRecord.default_factory`.

Schemas (`_CROSS_SCHEMA`, `_OUTPUT_SCHEMA`) are derived from the domain
dataclasses via `SparkSchemaMixin.spark_schema()` — single source of truth.

Memory note: each row carries the full model blob. At pandas→Arrow
serialization (mapInPandas yield), Arrow materializes each row's bytes
separately — no dedup. So a per-yield buffer of N rows allocates N × blob_size
of Arrow memory. Tune `_YIELD_CHUNK` to keep N × blob_size within worker
memory. The default of 100 assumes ~5MB blobs (~500MB per yield); lower it
when the model serializes larger, or Python workers will be OOM-killed
mid-stream (surfaces as a JVM socket reset).
"""
from __future__ import annotations

from itertools import product
from typing import Iterator

import pandas as pd
from pyspark.sql import DataFrame, SparkSession

from dbrx_multimodel_registration.domains.entities import (
    GenerationSpec,
    RunPlanKey,
    TrainedModelRecord,
)


_CROSS_SCHEMA = RunPlanKey.spark_schema()
_OUTPUT_SCHEMA = TrainedModelRecord.spark_schema()
# Small on purpose: per-yield Arrow buffer is roughly _YIELD_CHUNK * blob_size.
# 100 × 5MB ≈ 500MB per yield, well within standard worker memory.
_YIELD_CHUNK = 100


class TrainingSimulator:
    """`TrainingSimulatorPort` — emits the run-plan DataFrame with model bytes per row."""

    name = "broadcast_reuse"

    def __init__(self, spark: SparkSession, partitions: int | None = None) -> None:
        self.spark = spark
        self.partitions = partitions

    def simulate(
        self,
        reference_model_bytes: bytes,
        spec: GenerationSpec,
        model_names: list[str],
    ) -> DataFrame:
        bc = self.spark.sparkContext.broadcast(reference_model_bytes)
        cross = [(r, s, m) for r, s, m in product(spec.regions, spec.skus, model_names)]
        # Scale partitions with cluster parallelism so the mapInPandas fan-out
        # saturates workers. Previous formula `len(spec.regions) * 4` gave 20
        # partitions on a 5-region cluster — fine at 1k SKU but starved at 20k+.
        parts = self.partitions or self.spark.sparkContext.defaultParallelism * 4
        plan_df = self.spark.createDataFrame(cross, schema=_CROSS_SCHEMA).repartition(parts)

        def _emit(itr: Iterator[pd.DataFrame]) -> Iterator[pd.DataFrame]:
            # ─── Customization point ──────────────────────────────────────
            # `model_training_fn` is the seam where real training would live.
            # Today it just reads the broadcast value of the reference model
            # (originally pickled in Stage 2 and saved to a UC Volume) — every
            # call returns the same bytes, which is what makes this a
            # "simulator." Swap the body for a real `fit(...) → pickle.dumps`
            # to convert this into an actual distributed trainer without
            # touching the surrounding pandas_udf scaffolding.
            def model_training_fn(region: str, sku: str, model_name: str) -> bytes:
                return bc.value
            # ──────────────────────────────────────────────────────────────

            for batch in itr:
                buffer: list[dict] = []
                for region, sku, model_name in zip(
                    batch["region"], batch["sku"], batch["model_name"]
                ):
                    model_bytes = model_training_fn(region, sku, model_name)
                    rec = TrainedModelRecord(
                        region=region,
                        sku=sku,
                        model_name=model_name,
                        model_blob_bytes=model_bytes,
                    )  # params + metrics auto-generated by default_factory on the worker
                    # Column names match TrainedModelRecord field names (the schema
                    # is derived from the dataclass via `SparkSchemaMixin`).
                    buffer.append(
                        {
                            "region": rec.region,
                            "sku": rec.sku,
                            "model_name": rec.model_name,
                            "model_blob_bytes": rec.model_blob_bytes,
                            "params": rec.params,
                            "metrics": rec.metrics,
                        }
                    )
                    if len(buffer) >= _YIELD_CHUNK:
                        yield pd.DataFrame(buffer)
                        buffer = []
                if buffer:
                    yield pd.DataFrame(buffer)

        return plan_df.mapInPandas(_emit, schema=_OUTPUT_SCHEMA)
